language: php

php:
  - 5.4

before_script:
  #- pyrus install pear/PHP_CodeSniffer-1.5.3
  #- phpenv rehash
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl php5-gd > /dev/null

  # XVFB
  - "export DISPLAY=:99.0"
  - "Xvfb :99.0 -extension RANDR > /dev/null &"

  # Window manager
  - echo "c10"
  - "sudo apt-get install fluxbox -y --force-yes"
  - echo "c11"
  - "fluxbox &"

  # Selenium server
  - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar -O selenium-server-standalone.jar
  - "java -jar selenium-server-standalone.jar > /dev/null 2>/dev/null &"
  - sh .travis/wait4selenium.sh

  # Composer
  - composer self-update
  - composer update

  # Joomla Console Installation
  - cd vendor/
  - git clone https://github.com/ijoomer-advance/joomla-console.git
  - sudo chmod u+x /home/travis/build/ijoomer-advance/ijoomer-adv-joomla/vendor/joomla-console/bin/joomla
  - sudo ln -s /home/travis/build/ijoomer-advance/ijoomer-adv-joomla/vendor/joomla-console/bin/joomla /usr/bin/joomla
  - export PATH="$PATH:/home/travis/build/ijoomer-advance/ijoomer-adv-joomla/vendor/joomla-console/bin:/usr/local/bin"
  - alias joomla=/home/travis/build/ijoomer-advance/ijoomer-adv-joomla/vendor/joomla-console/bin/joomla
  #- which joomla
  - cd joomla-console
  - composer install
  - cd /home/travis/build/ijoomer-advance/ijoomer-adv-joomla/
  #- joomla --list

script:

  # Install Joomla site
  - sudo joomla site:create jcms3.4

  # PHP Code Sniffer for code style verification
  #- phpcs --report=summary --extensions=php -p -n --standard=.build/phpcs/Joomla plugins/
  #- phpcs --report=summary --extensions=php -p -n --standard=.build/phpcs/Joomla component/

  # Create travis system tests config file
  - mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml

  # Get Joomla CMS for System Tests
  #- php vendor/phing/phing/bin/phing -f tests/getjoomla.xml

  # Execure codeception suits
  - php vendor/bin/codecept build
  - php vendor/bin/codecept run --steps
